import time
import subprocess
import os
import threading
from playwright.sync_api import sync_playwright

def pipe_output(proc):
    for line in iter(proc.stdout.readline, b''):
        print(f"[Server] {line.decode().strip()}")

def run_test():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    # 1. Start the HTTP Server and Python signaling server
    print('Starting Python servers...')
    http_process = subprocess.Popen(
        ['python', '-m', 'http.server', '8000'],
        cwd=base_dir,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )
    
    server_process = subprocess.Popen(
        ['python', 'server.py'],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        cwd=base_dir
    )
    
    threading.Thread(target=pipe_output, args=(server_process,), daemon=True).start()
    time.sleep(3) # Give servers a moment to bind

    with sync_playwright() as p:
        try:
            # 2. Launch browser with special flags
            browser = p.chromium.launch(
                args=[
                    '--use-fake-ui-for-media-stream',
                    '--use-fake-device-for-media-stream'
                ]
            )

            # 3. Create Contexts
            dentist_context = browser.new_context()
            dentist_page = dentist_context.new_page()
            dentist_page.on('console', lambda msg: print(f"Dentist Console: {msg.text}"))

            superior_context = browser.new_context()
            superior_page = superior_context.new_page()
            superior_page.on('console', lambda msg: print(f"Superior Console: {msg.text}"))

            ROOM_ID = 'test-room-4890'
            PIN = '9999'

            # --- DENTIST FLOW ---
            print('Dentist: Opening page...')
            dentist_page.goto("http://localhost:8000/dentist.html")

            # Enter Room ID & PIN
            dentist_page.fill('#roomId', ROOM_ID)
            dentist_page.fill('#roomPin', PIN)

            # Start Cameras
            print('Dentist: Starting cameras...')
            dentist_page.click('#startCamerasBtn')

            # Wait for video
            dentist_page.wait_for_function('''() => {
              const video = document.querySelector('#pcFeedPlaceholder video');
              return video && video.currentTime > 0;
            }''', timeout=5000)

            # Create Room
            print('Dentist: Creating room...')
            dentist_page.click('#createRoomBtn')

            # Assert: Dentist Workspace
            print('Dentist: Waiting for Room ID to be populated by server...')
            dentist_page.wait_for_function("() => document.getElementById('roomPin').hasAttribute('readonly')")
            print('Dentist: WebSocket is CONNECTED and Room is ready.')

            # The PIN is randomly generated by the server, so we must extract it from the DOM
            generated_pin = dentist_page.input_value('#roomPin')
            print(f'Dentist: Received PIN {generated_pin}.')

            # --- SUPERIOR FLOW ---
            print('Superior: Opening page...')
            superior_page.goto("http://localhost:8000/superior.html")

            superior_page.fill('#roomId', ROOM_ID)
            superior_page.fill('#roomPin', generated_pin)

            print('Superior: Joining room...')
            superior_page.click('#joinRoomBtn')

            # Assert: Superior WebSocket
            superior_page.wait_for_function('''() => {
              return typeof socket !== "undefined" && socket && socket.readyState === 1;
            }''')
            print('Superior: WebSocket is CONNECTED.')


            # --- WEBRTC VERIFICATION ---
            print('Waiting for remote video to render and play...')
            superior_page.wait_for_function('''() => {
              const video = document.querySelector('#mainVideoContainer video');
              if (!video) return false;
              return video.srcObject !== null && video.currentTime > 0;
            }''', timeout=30000)
            
            print('Superior: Remote video stream is actively playing!')
            print('✅ All Verifications Passed!')

        finally:
            if 'browser' in locals():
                browser.close()
            print('Shutting down servers...')
            server_process.terminate()
            http_process.terminate()

if __name__ == '__main__':
    run_test()
